ALTER TABLE hub_external_resources 
ADD COLUMN IF NOT EXISTS prize_pool TEXT,
ADD COLUMN IF NOT EXISTS team_size TEXT,
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS rating TEXT,
ADD COLUMN IF NOT EXISTS enrolled_count TEXT,
ADD COLUMN IF NOT EXISTS certificate_offered BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS price TEXT;
